ExpenseTracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('transactions/', include('transactions.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

transactions/urls.py
from django.urls import path
from . import views

app_name = "transactionsApp"
urlpatterns = [
    # * ex: /transactions/
    path('', views.IndexView.as_view(),name='index'),
    # * ex: /transactions/5
    path('<int:category_id>/', views.details,name='details'),
    # * ex: /transactions/details_category/5
    path('details_category/<slug:slug>/', views.DetailsCategoryView.as_view(),name='details_category'),
     # * ex: /transactions/details_consult_transaction/5
    path('details_consult_transaction/<int:category_id>/', views.details_consult_transaction,name='details_consult_transaction'),
     # * ex: /transactions/details_results_category/5
    path('details_results_category/<slug:slug>/', views.DetailsResultsCategoryView.as_view(),name='details_results_category'),
]

transactions/models.py
from datetime import date,timedelta
from django.db import models

class Category(models.Model):
    name = models.CharField('Category Name', max_length=50)
    description = models.CharField(max_length=250)

    def __str__(self):
        return self.name

class TypeTransaction(models.IntegerChoices):
    EXPENSE = 0, 'Expense'
    REVENUE = 1, 'Revenue'

class Transaction(models.Model):
    category = models.ForeignKey('Category', on_delete=models.RESTRICT)
    date = models.DateField('date transaction')
    amount = models.DecimalField(max_digits=5,decimal_places=2)
    note = models.CharField(max_length=250)
    type = models.IntegerField(default=TypeTransaction.EXPENSE, choices=TypeTransaction.choices)
    counter = models.IntegerField(default=0)

    def __str__(self):
        if (self.type == TypeTransaction.EXPENSE):
            return "Gasto, {} {}".format(self.note,self.amount)
        elif(self.type == TypeTransaction.REVENUE):
            return "Ingreso, {} {}".format(self.note,self.amount)
        
    def is_recent_date_of_transaction(self):
        '''Return if the transaction date is less than 5 days ago'''
        return date.today() >= self.date >= date.today() - timedelta(days=5)

    class Meta:
        permissions = (("can_see_results", "See the counter of the transactions in the result screen"),
                       ("can_consult_transaction", "Consult the transaction to display the list of transactions"))    

transactions/views.py
from datetime import date

from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse,HttpResponseRedirect
from django.urls import  reverse
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Category,Transaction

class IndexView(LoginRequiredMixin,generic.ListView):
    template_name = 'transactions/index.html'
    context_object_name = 'category_list'
    #login_url = 'accounts/login'
    #redirect_field_name = 'next'
    
    def get_queryset(self):
        return Category.objects.order_by("name")
        #Para obtener las 5 primeras categorias por fecha ordenada y de mas recientes a mas antiguas
        #return Category.objects.order_by("-pub_date")[:5]

# ListView
# def index(request):
#     context = {
#         'category_list': Category.objects.all()
#     }
#     return render(request,'transactions/index.html',context)

# class DetailsView(generic.DetailView):
#     model = Category
#     template_name = 'transactions/details.html'
#     slug_field = 'id'


#DetailView
@login_required
def details(request,category_id):
    context = {
        'category': get_object_or_404(Category,pk=category_id),
        'transactions': get_object_or_404(Category,pk=category_id).transaction_set.filter(date__lte=date.today()).order_by('-date')
    }
    return render(request,'transactions/details.html',context)

class DetailsCategoryView(LoginRequiredMixin,generic.DetailView):
    model = Category
    template_name = 'transactions/details_category.html'
    slug_field = 'id'

#DetailView
# def details_category(request,category_id):
#     context = {
#         'category': get_object_or_404(Category,pk=category_id)
#     }
#     return render(request,'transactions/details_category.html',context)

@login_required
def details_consult_transaction(request,category_id):
    category = get_object_or_404(Category,pk=category_id)
    try:
        #Toma el valor de value del input, en base al name, request.POST['transaction']
        transaction = category.transaction_set.get(pk=request.POST['transaction'])
    #Controlar estos 2 tipos de errores
    except (KeyError,Transaction.DoesNotExist):
        context = { 
            'category': category,
            'error_message':'No se ha seleccionado una transacción antes de mandar a consultar.'
        }
        return render(request,'transactions/details_category.html',context)
    else:
        transaction.counter += 1
        transaction.save()
        return HttpResponseRedirect(reverse('transactionsApp:details_results_category',args=(category.id,)))

class DetailsResultsCategoryView(LoginRequiredMixin,generic.DetailView):
    model = Category
    template_name = 'transactions/results.html'
    slug_field = 'id' 

#DetailView    
# def details_results_category(request,category_id):
#     context = {
#         'category': get_object_or_404(Category,pk=category_id)
#     }
#     return render(request,'transactions/results.html',context)

transactions/templates/transactions/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel='stylesheet' href="{% static 'transactions/reset.css' %}">
    <link rel='stylesheet' href="{% static 'transactions/style.css' %}">
</head>
<body>
    <header>
        <h1>Aplicacion de control de gastos e ingresos</h1>
    </header>
    <main>
        <ul class="sidebar-nav">
            {% if user.is_authenticated %}
                <li>User: {{ user.get_username }}</li>
                <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
            {% else %}
                <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
            {% endif %}
        </ul>
        <div id="content">
            {% block content %}
            {% endblock %}
        </div>
    </main>
    <footer>
        <a href="{% url 'transactionsApp:index' %}">Home</a>
        <a href="#">Contacto</a>
        <a href="#">Politica de privacidad</a>
        <a href="#">Terminos y condiciones</a>
    </footer>
</body>
</html>

transactions/templates/transactions/details.html
{% extends "transactions/base.html" %}
{% block title %}{{category.name}}{% endblock %}
{% block content %}
    {% if category %}
        <h1 class='niceTitle'>Listado de transacciones de la categoria {{category.name}}</h1>
        <ul>
        {% if transactions %}
            {% for transaction in transactions  %}
                <li>{{transaction.date}} {{transaction.amount}} {{transaction.note}}</li>    
            {% endfor %}
        {% else %}
            <p><strong>No hay transacciones para esta categoría</strong></p>
        {% endif %}
        </ul>
    {% endif %}
    <br>
    <a href="{% url 'transactionsApp:details_category' category.id %}" class='bright'>Consultar las transacciones</a>
{% endblock %}

transactions/templates/transactions/details_category.html
{% extends "transactions/base.html" %}
{% block title %}Consultar de: {{category.name}}{% endblock %}
{% block content %}
    {% if perms.transactions.can_consult_transaction %}
        <form action="{% url 'transactionsApp:details_consult_transaction' category.id %}" method='post'>
            {% csrf_token %}
            <fieldset>
                <legend>
                    <h1>{{category.name}}</h1>
                    {% if error_message%}
                        <p><strong>{{error_message}}</strong></p>
                    {% endif %}
                </legend>
                {% for transaction in category.transaction_set.all  %}
                    <input 
                        type='radio'
                        name='transaction'
                        id='transaction{{ forloop.counter }}'
                        value='{{transaction.id}}'
                    >
                    <label for="transaction{{ forloop.counter }}">
                        {{ transaction.note }}
                    </label>
                    <br>
                {% endfor %}
            </fieldset>
            <input type="submit" value='Consultar transaccion'>
        </form>
    {% else %}
        <p><strong>Lo sentimos tu usuario no tiene el permiso de consultar las transacciones en detalle</strong></p>
    {% endif %}
{% endblock %}

transactions/templates/transactions/details_dates.html
<form action="{% url 'transactionsApp:details_dates_transaction' category.id %}" method='post'>
    {% csrf_token %}
    <fieldset>
        <legend>
            <h1>{{category.name}}</h1>
            {% if error_message%}
                <p><strong>{{error_message}}</strong></p>
            {% endif %}
        </legend>
        {% for transaction in category.transaction_set.all  %}
            <input 
                type='radio'
                name='transaction'
                id='transaction{{ forloop.counter }}'
                value='{{transaction.id}}'
            >
            <label for="transaction{{ forloop.counter }}">
                {{ transaction.note }}
            </label>
            <br>
        {% endfor %}
    </fieldset>
    <input type="submit" value='Detalle'>
</form>

transactions/templates/transactions/index.html
{% extends "transactions/base.html" %}
{% block title %}My amazing app{% endblock %}
{% block content %}
    {% if category_list %}
        <h1 class='niceTitle'>Listado de categorias</h1>
        <ul>
        {% for category in category_list  %}
            <li><a href="{% url 'transactionsApp:details' category.id %}">{{category.name}}</a></li>    
        {% endfor %}
    </ul>
    {% else %}
        <p>No hay categorias registradas en el sistema aún...</p>
    {% endif %}
{% endblock %}

transactions/templates/transactions/results.html
{% extends "transactions/base.html" %}
{% block title %}Revision de: {{category.name}}{% endblock %}
{% block content %}
    {% if perms.transactions.can_see_results %}
        <h1 class='niceTitle'>{{category.description}}</h1>
        <ul>
        {% for transaction in category.transaction_set.all  %}
            <li>{{transaction.note}} tiene {{transaction.counter}} consulta{{transaction.counter|pluralize:',s'}}</li>
        {% endfor %}
        </ul>
        <br>
    {% else %}
        <p><strong>Lo sentimos tu usuario no tiene el permiso de ver el total de veces que han sido consultas las transacciones</strong></p>
    {% endif %}
    <a href="{% url 'transactionsApp:details_category' category.id %}" class='bright'>Quieres volver a el listado de transacciones por categoria</a>
{% endblock %}